name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build and push the testserial image
      run: 
        hash_ts=$(git rev-parse --short HEAD)
        docker ./TestSerial build --platform linux/arm64 -t ecy14mhfh/testserial:$hash_ts -f Dockerfile .
        docker push ecy14mhfh/testserial:$hash_ts
        echo $hash_ts
        #docker build ./TestSerial --platform linux/arm64 -t ecy14mhfh/testserial:$(date +%s)

    - name: Build and push the pihattest image
      run: 
        docker build ./pihattest --platform linux/arm64 -t ecy14mhfh/pihattest:$(date +%s)

