name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the testserial image
      run: 
        # Can I run bash commands here?
        bash ts_builddocker.sh
