name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # run: |
      #   docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build and push testserial
      uses: docker/build-push-action@v3
      with:
        context: ./TestSerial/
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: user/app:latest

    # - name: Build and push pihattest
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: ./chiaedgetestingspace/pihattest
    #     platforms: linux/amd64,linux/arm64
    #     #file: ./TestSerial
    #     push: true
    #     tags: user/app:latest
    
    # - name: Build and push the pihattest image
    #   run: 
    #     docker build ./pihattest --platform linux/arm64 -t ecy14mhfh/pihattest:$(date +%s)

